services:
  db:
    image: postgres
    container_name: postgres_db
    environment:
      POSTGRES_DB: ceres_db
      POSTGRES_USER: ceres_user
      POSTGRES_PASSWORD: ceres_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@ceres.com
      PGADMIN_DEFAULT_PASSWORD: ceres
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data:
